### PR TITLE
Workshop

### PR DESCRIPTION
**Pull request by BigBossRabbit**
Think I might have got the connection & pull request to synch from my IDE.

### CODE REVIEW

**Comment by mandelmonkey** [comment]
@BigBossRabbit i am not involved with submissions but I will try and check with the organizers to see if they got yours

**Comment by BigBossRabbit** [comment]
Oh, my apologies. I thought that I was supposed to submit it this way. Thank you for any assistance and for a wonderful project which has taught me a great deal about Bitcoin LN integration.

**Comment by mandelmonkey** [comment]
glad you found it useful!

**Comment by BigBossRabbit** [comment]
I really did. Going to work at understanding how to replace the QR code with a Lightning Address integration, as I'm trying to learn how to do this on websites and almost any app through practical examples.

**Pull request closed without merging**
